### PR TITLE
Update esbuild version

### PR DESCRIPTION
**Pull request by JBerendes**
Hi Nick, 

I like what you have going here. And I'm hoping to contribute where I can as I'm starting a new project soon and likely using this as the base. So here is a relatively safe PR to get started.

Thanks much!

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Thanks!

Can you please:

- Update the `CHANGELOG.md` file under the unreleased front-end dependencies to change esbuild from `0.19.2` to `0.19.3`?
- Amend the git commit message to "Update esbuild version"

**Comment by JBerendes** [comment]
> Hi,
> 
> Thanks!
> 
> Can you please:
> 
> * Update the `CHANGELOG.md` file under the unreleased front-end dependencies to change esbuild from `0.19.2` to `0.19.3`?
> * Amend the git commit message to "Update esbuild version"

Done as requested.

**Comment by JBerendes** [comment]
i tried to squash and amend but the commits now look dirty rather than just being one commit message. I'm not quite sure why. I'm tempted to just create a new clean PR.

**Comment by nickjj** [comment]
You can `git commit --amend`, write the new message and then `git push origin main --force` on this PR.

**Comment by JBerendes** [comment]
got sorted a bit differently but thanks for the suggestions.

**Comment by nickjj** [comment]
Thanks!

**Pull request merged**
