### PR TITLE
Add yarn:add command to add NPM package

### PR DESCRIPTION
**Pull request by saiqulhaq**
Do you think the readme file update is correct?

### CODE REVIEW

**Comment by nickjj** [comment]
Hi,

Normally to add a new dependency I'd add the package to `package.json` and then run `./run yarn:install`. That will ensure the following:

- The new package is referenced
- A new Docker image gets built
- A new `yarn.lock` file gets volume mounted out so you can commit it

Are you using a different workflow?

**Comment by saiqulhaq** [comment]
adding a new package to package.json file means I have to know what is the latest version
`yarn add xxx` will install the latest version
which is a common workflow, where we normally install the latest version
`yarn add` is the same as `bundle add`

**Comment by nickjj** [comment]
If you make a change to the running container with add and then stop the container, do you have re-run `./run yarn:install` before the next time you start the container? Otherwise you would lose whatever was installed in the image since it was adjusted at runtime in the previously running container.

I think I'd prefer having a shortcut for `./run yarn <...>` where you can run anything. The only reason `yarn:install` exists is because it does a few other things besides installing to ensure the lock file gets written out.

**Comment by saiqulhaq** [comment]
I don't need to run `yarn:install` command, since `yarn:add` will update the package.json and yarn.lock files.
so in the next run, `docker compose up --build` will automatically install the dependencies during the image building process. the new running container should able to run without any issue.
if using `_build_run_down` command, it would take a very long time to just add a single NPM package.

I am not sure about another `yarn`'s command. I worry that the command affects the current running container only.

**Comment by nickjj** [comment]
Right, but the takeaway there is you need to run `up --build` or `build` after add so you end up having to wait some time for that.

**Comment by saiqulhaq** [comment]
oh ok, then let me close this PR
since it's not suitable for everyone
I always run `up --build` in my development workflow
thanks a lot for the feedback

**Comment by nickjj** [comment]
No problem. Thanks for opening this tho!

**Comment by lesterzone** [comment]
I came here for this `...means I have to know what is the latest version
yarn add xxx will install the latest version`

I just added a new run command:

```sh
function yarn:add {
  # Add dependencies to our package.json
  _build_run_down js yarn add "${1}"
}
```

Just because I want to add the dependency with the version to `package.json`

**Comment by nickjj** [comment]
Yep that works. Also for keeping things up to date you can run `./run yarn:outdated` to get a list of outdated dependencies. Likewise the `bundle:outdated` exists too.

**Pull request closed without merging**
